import 'dart:async';

import 'package:admin/app/app.export.dart';
import 'package:admin/app/constant/FontConstant.dart';
import 'package:flutter/material.dart';

class ThemeHelper {
  static StreamController<String> controller = StreamController<String>();

  static BaseTheme? theme() => _getDefaultTheme();

  static String? _appTheme;

  static Stream<String> appthemeString = controller.stream;

  static Map<String, BaseTheme> _supportedThemes = {
    "white": BaseTheme(),
    "dark": DarkTheme(),
    "custom": CustomTheme(),
  };

  static BaseTheme? _getDefaultTheme() {
    //return default strings if locale is not set

    if (_appTheme == null) return BaseTheme();

    //throw exception to notify given local is not found or not generated by the generator

    if (!_supportedThemes.containsKey(_appTheme))
      throw Exception(
          "$_appTheme is not found.\n Make sure you have added this locale in JSON file\n Try running flutter pub run build_runner");

    //return locale from map

    return _supportedThemes[_appTheme!];
  }

  static void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
    controller.add(_newTheme);
  }
}

class DarkTheme extends BaseTheme {
  @override
  Color get colorPrimary => Colors.pink;
}

class CustomTheme extends BaseTheme {
  @override
  Color get colorPrimary => fromHex("#4EB45E");
  @override
  Color get selectedFilterColor => fromHex("#F2FCF4");

  @override
  Color get unSelectedBgColor => fromHex("#f7f7f7");
}

class BaseTheme {
  Color get colorPrimary => fromHex("#294572");
  Color get colorGreen => fromHex("#00A83E");
  Color get textColor => fromHex("#353535");

  Color get textBlueColor => fromHex("#0132A8");

  Color get grey => fromHex("#666666");

  // Color get textBlackColor => Colors.black;
  Color get blackColor => Colors.black;
  Color get whiteColor => Colors.white;
  Color get textDarkGreyColor => fromHex("#7C7C7C");
  Color get accountTextColor => fromHex("#03070F");
  Color get accountTextGreyColor => fromHex("#686868");
  Color get passportTextColor => fromHex("#1C1C1C");

  Color get buttonBGColor => fromHex("#1E3F8E");
  Color get borderColor => fromHex("#E8E6EA");

  Color get searchBackgroundColor => fromHex("#F8F9FB");

  Color get introBlueColor => fromHex("#001D63");
  Color get darkYellow => fromHex("#E8992A");

  Color get starFillColor => fromHex("#EAA441");

  // Color get buttonColor => fromHex("#6E8FE7");
  // Color get darkBlue => fromHex("#003365");
  // Color get errorColor => fromHex("#FF4D4D");
  // Color get segmentSelectedColor => Colors.white;
  //
  // Color get selectedFilterColor => fromHex("#eaeffb");
  // Color get unSelectedBgColor => fromHex("#f7f7f7");
  // Color get greenColor => fromHex("#0EAC33");
  // Color get lightBGColor => fromHex("#F8F8F8");
  Color get colorOTPTextfieldBG => fromHex("#F5F5F5");
  Color get colorTextField => fromHex("#EDF0F4");
  Color get colorTextFieldBorder => fromHex("#EDF0F4");
  // Color get statusHold => fromHex("#DB1C1C");
  // Color get statusOnMemo => fromHex("#307BEA");
  // Color get statusAvailable => fromHex("#6BC950");
  // Color get statusNew => fromHex("#B256E6");
  // Color get statusOffer => fromHex("#FF4DB8");
  // Color get statusMyHold => fromHex("#F1951E");
  Color get textGray => fromHex("#9E9E9E");
  // Color get drawerTitleColor => fromHex("#EEF1FC");
  // Color get lightColorPrimary => fromHex("#EEF1FC");
  Color get redColor => fromHex("#AC0000");
  // Color get whatsAppColor => fromHex("#55CD6C");
  // Color get gmailColor => fromHex("#DB4436");
  // Color get skypeColor => fromHex("#03A9F4");
  Color get introgrey => fromHex("#999999");

  Color get sepratorColor => fromHex("#AFAFAF");

  Color get hintColor => fromHex("#CCCCCC");
  Color? get dividerColor => Colors.grey[100];

  Color get pendingTextColor => fromHex("#EFBB71");
  Color get paidTextColor => fromHex("#00AE29");
  Color get completeTextColor => fromHex("#1E3F8E");
  Color get processingTextColor => fromHex("#EB61F5");
  Color get cancelledTextColor => fromHex("#DC0101");

  Color get shadowColorWithoutOpacity => fromHex("#000000").withOpacity(0.1);
  Color get shadowColor => shadowColorWithoutOpacity.withOpacity(0.1);
  // Color get shadowColor => fromHex("#7D9EF61A");

  Color get trackCurrentColor => fromHex("#34A9E0");
  Color get trackCompletedColor => fromHex("#1E3F8E");
  Color get trackPendingColor => fromHex("#686868");

  Color get toastColor => fromHex("#EFEFEF");

  Color get passportCellBGColor => fromHex("#F9F9F9");

  Color get tagBGColor => fromHex("#E6E9F2");

  Color get documentCountBGColor => fromHex("#8294C0");

  Color get appliedStatusColor => fromHex("#532BFC");
  Color get scheduledStatusColor => fromHex("#459BD5");
  Color get hiredStatusColor => fromHex("#52D44D");
  Color get notSelectedStatusColor => fromHex("#D44D4D");

  Color get linkedInColor => fromHex("#004182");

  Color get splashBgColor => fromHex("#ECF0F2");
  // grey14TextStyle

  TextStyle get buttonTitle14TextStyle {
    return TextStyle(
      fontSize: getFontSize(14),
      fontWeight: FontWeight.w400,
      color: whiteColor,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text10Primary {
    return TextStyle(
      fontFamily: Regular,
      fontSize: getFontSize(10),
      fontWeight: FontWeight.w400,
      color: colorPrimary,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text10Black {
    return TextStyle(
      fontFamily: Regular,
      fontSize: getFontSize(10),
      fontWeight: FontWeight.w400,
      color: blackColor,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text9WhiteSemi {
    return TextStyle(
      fontFamily: Semibold,
      fontSize: getFontSize(9),
      fontWeight: FontWeight.w600,
      color: whiteColor,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text10WhiteSemi {
    return TextStyle(
      fontFamily: Semibold,
      fontSize: getFontSize(10),
      fontWeight: FontWeight.w600,
      color: whiteColor,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text9PrimeSemi {
    return TextStyle(
      fontFamily: Semibold,
      fontSize: getFontSize(9),
      fontWeight: FontWeight.w600,
      color: colorPrimary,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text9BlackSemi {
    return TextStyle(
      fontFamily: Semibold,
      fontSize: getFontSize(9),
      fontWeight: FontWeight.w600,
      color: blackColor,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text7BlackRegular {
    return TextStyle(
      fontFamily: Regular,
      fontSize: getFontSize(7),
      fontWeight: FontWeight.w400,
      color: blackColor,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text10Grey {
    return TextStyle(
      fontFamily: Regular,
      fontSize: getFontSize(10),
      fontWeight: FontWeight.w400,
      color: grey,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text10BlackRegular {
    return TextStyle(
      fontFamily: Regular,
      fontSize: getFontSize(10),
      fontWeight: FontWeight.w400,
      color: blackColor,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text11BlackRegular {
    return TextStyle(
      fontFamily: Regular,
      fontSize: getFontSize(11),
      fontWeight: FontWeight.w400,
      color: blackColor,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text11PrimaryRegular {
    return TextStyle(
      fontFamily: Regular,
      fontSize: getFontSize(11),
      fontWeight: FontWeight.w400,
      color: colorPrimary,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text11PrimaryBold {
    return TextStyle(
      fontFamily: Regular,
      fontSize: getFontSize(11),
      fontWeight: FontWeight.w600,
      color: colorPrimary,
      letterSpacing: 0.56,
    );
  }

  TextStyle get text13Black {
    return TextStyle(
        fontSize: getFontSize(13),
        fontWeight: FontWeight.w400,
        color: blackColor,
        letterSpacing: 0.56,
        fontFamily: Regular);
  }

  TextStyle get text13PrimarySemi {
    return TextStyle(
        fontSize: getFontSize(13),
        fontWeight: FontWeight.w600,
        color: colorPrimary,
        letterSpacing: 0.56,
        fontFamily: Regular);
  }

  TextStyle get text14IntroGreyText {
    return TextStyle(
        fontSize: getFontSize(14),
        fontWeight: FontWeight.w400,
        color: introgrey,
        letterSpacing: 0.56,
        fontFamily: Regular);
  }

  TextStyle get text18PrimarySemi {
    return TextStyle(
        fontSize: getFontSize(18),
        fontWeight: FontWeight.w600,
        color: colorPrimary,
        letterSpacing: 0.56,
        fontFamily: Regular);
  }

  TextStyle get buttonTitle18TextStyle {
    return TextStyle(
      fontSize: getFontSize(18),
      fontWeight: FontWeight.w400,
      color: colorPrimary,
      fontFamily: Semibold,
      letterSpacing: 0.68,
    );
  }

  TextStyle get buttonBGColor18Semibold {
    return TextStyle(
        fontSize: getFontSize(18),
        color: buttonBGColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get textColor26Light {
    return TextStyle(
        fontSize: getFontSize(26),
        fontWeight: FontWeight.w300,
        color: textColor);
  }

  TextStyle get textColor26Bold {
    return TextStyle(
        fontFamily: Bold,
        fontSize: getFontSize(26),
        fontWeight: FontWeight.w700,
        color: textColor);
  }

  TextStyle get textBlack30Bold {
    return TextStyle(
        fontFamily: Bold,
        fontSize: getFontSize(30),
        fontWeight: FontWeight.w700,
        color: blackColor);
  }

  TextStyle get text30PrimarySemi {
    return TextStyle(
        fontFamily: Bold,
        fontSize: getFontSize(30),
        fontWeight: FontWeight.w700,
        color: colorPrimary);
  }

  TextStyle get text35PrimarySemi {
    return TextStyle(
        fontFamily: Bold,
        fontSize: getFontSize(35),
        fontWeight: FontWeight.w700,
        color: colorPrimary);
  }

  TextStyle get blackColor22SemiBold {
    return TextStyle(
        fontFamily: Bold,
        fontSize: getFontSize(22),
        fontWeight: FontWeight.w600,
        color: blackColor);
  }

  TextStyle get blackColor24SemiBold {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(24),
        fontWeight: FontWeight.w600,
        color: blackColor);
  }

  TextStyle get primary20Semibold {
    return TextStyle(
        fontSize: getFontSize(20),
        color: colorPrimary,
        fontWeight: FontWeight.w600);
  }

  TextStyle get white22Normal {
    return TextStyle(
        fontSize: getFontSize(22),
        fontWeight: FontWeight.w400,
        color: whiteColor);
  }

  TextStyle get whiteNormal18 {
    return TextStyle(
        fontSize: getFontSize(18),
        fontWeight: FontWeight.normal,
        color: whiteColor);
  }

  TextStyle get black18Bold {
    return TextStyle(
        fontSize: getFontSize(18),
        color: blackColor,
        fontWeight: FontWeight.w700);
  }

  TextStyle get black18Semibold {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(18),
        color: blackColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get textColor16Normal {
    return TextStyle(
        fontFamily: Regular,
        fontSize: getFontSize(16),
        fontWeight: FontWeight.w400,
        color: colorPrimary);
  }

  TextStyle get text16SemiPrimary {
    return TextStyle(
        fontFamily: Regular,
        fontSize: getFontSize(16),
        fontWeight: FontWeight.w600,
        color: colorPrimary);
  }

  TextStyle get textColor16SemiBold {
    return TextStyle(
        fontFamily: Regular,
        fontSize: getFontSize(16),
        fontWeight: FontWeight.w600,
        color: colorPrimary);
  }

  TextStyle get textColor16Grey {
    return TextStyle(
        fontFamily: Regular,
        fontSize: getFontSize(16),
        fontWeight: FontWeight.w400,
        color: grey);
  }

  TextStyle get white16Normal {
    return TextStyle(
        fontSize: getFontSize(16),
        fontWeight: FontWeight.w400,
        color: whiteColor);
  }

  TextStyle get black16Medium {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(16),
        fontWeight: FontWeight.w500,
        color: blackColor);
  }

  TextStyle get black16Semibold {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(16),
        color: blackColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get accountTextColor16Normal {
    return TextStyle(
        fontSize: getFontSize(16),
        color: accountTextColor,
        fontWeight: FontWeight.w400);
  }

  TextStyle get accountTextColor16Semibold {
    return TextStyle(
        fontSize: getFontSize(16),
        color: accountTextColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get accountTextColor16Bold {
    return TextStyle(
        fontSize: getFontSize(16),
        color: accountTextColor,
        fontWeight: FontWeight.w700);
  }

  TextStyle get passportTextColor16Semibold {
    return TextStyle(
        fontSize: getFontSize(16),
        color: passportTextColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get blue14Bold {
    return TextStyle(
        fontSize: getFontSize(14),
        color: textBlueColor,
        fontWeight: FontWeight.w700);
  }

  TextStyle get black14Semibold {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(14),
        color: blackColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get black14Normal {
    return TextStyle(
        fontSize: getFontSize(14),
        color: blackColor,
        fontWeight: FontWeight.w400);
  }

  TextStyle get black14Light {
    return TextStyle(
        fontSize: getFontSize(14),
        color: blackColor,
        fontWeight: FontWeight.w300);
  }

  TextStyle get buttonBGColor14Bold {
    return TextStyle(
        fontSize: getFontSize(14),
        color: buttonBGColor,
        fontWeight: FontWeight.w700);
  }

  TextStyle get buttonBGColor14Semibold {
    return TextStyle(
        fontSize: getFontSize(14),
        color: buttonBGColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get textColor14Semibold {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(14),
        color: textColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get text14WhiteSemiBold {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(14),
        color: whiteColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get text14WhiteNormal {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(14),
        color: whiteColor,
        fontWeight: FontWeight.w400);
  }

  TextStyle get textPrimary14Semibold {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(14),
        color: colorPrimary,
        fontWeight: FontWeight.w600);
  }

  TextStyle get textColor14Normal {
    return TextStyle(
        fontFamily: Regular,
        fontSize: getFontSize(14),
        color: textColor,
        fontWeight: FontWeight.w400);
  }

  TextStyle get accountTextColor14Semibold {
    return TextStyle(
        fontSize: getFontSize(14),
        color: accountTextColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get completeTextColor14Semibold {
    return TextStyle(
        fontSize: getFontSize(14),
        color: completeTextColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get accountTextColor14Bold {
    return TextStyle(
        fontSize: getFontSize(14),
        color: accountTextColor,
        fontWeight: FontWeight.w700);
  }

  TextStyle get accountTextColor14Normal {
    return TextStyle(
        fontSize: getFontSize(14),
        color: accountTextColor,
        fontWeight: FontWeight.w400);
  }

  TextStyle get accountTextColor14Light {
    return TextStyle(
        fontSize: getFontSize(14),
        color: accountTextColor,
        fontWeight: FontWeight.w300);
  }

  TextStyle get textDarkGreyColor14Normal {
    return TextStyle(
        fontSize: getFontSize(14),
        fontWeight: FontWeight.w400,
        color: textDarkGreyColor);
  }

  TextStyle get textDarkGreyColor14Light {
    return TextStyle(
        fontSize: getFontSize(14),
        fontWeight: FontWeight.w300,
        color: textDarkGreyColor);
  }

  TextStyle get accountTextColor12Normal {
    return TextStyle(
        fontSize: getFontSize(12),
        color: accountTextColor,
        fontWeight: FontWeight.w400);
  }

  TextStyle get text12PrimaryMedium {
    return TextStyle(
        fontSize: getFontSize(12),
        color: colorPrimary,
        fontFamily: Semibold,
        fontWeight: FontWeight.w600);
  }

  TextStyle get text12WhiteMedium {
    return TextStyle(
        fontSize: getFontSize(12),
        color: whiteColor,
        fontFamily: Medium,
        fontWeight: FontWeight.w600);
  }

  TextStyle get text12WhiteNormal {
    return TextStyle(
        fontSize: getFontSize(12),
        color: whiteColor,
        fontFamily: Medium,
        fontWeight: FontWeight.w400);
  }

  TextStyle get text12GreyMedium {
    return TextStyle(
        fontSize: getFontSize(12),
        color: grey,
        fontFamily: Medium,
        fontWeight: FontWeight.w400);
  }

  TextStyle get text12GreenMedium {
    return TextStyle(
        fontSize: getFontSize(12),
        color: colorGreen,
        fontFamily: Regular,
        fontWeight: FontWeight.w400);
  }

  TextStyle get text12RegularBlack {
    return TextStyle(
        fontSize: getFontSize(12),
        color: blackColor,
        fontFamily: Regular,
        fontWeight: FontWeight.w400);
  }

  TextStyle get text12RedMedium {
    return TextStyle(
        // height: getSize(15),
        fontSize: getFontSize(12),
        color: colorPrimary,
        fontFamily: Regular,
        fontWeight: FontWeight.w400);
  }

  TextStyle get accountTextGreyColor12Normal {
    return TextStyle(
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w400,
        color: accountTextGreyColor);
  }

  TextStyle get accountTextGreyColor12Light {
    return TextStyle(
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w300,
        color: accountTextGreyColor);
  }

  TextStyle get accountTextColor12Light {
    return TextStyle(
        fontSize: getFontSize(12),
        color: accountTextColor,
        fontWeight: FontWeight.w300);
  }

  TextStyle get textDarkGreyColor12Normal {
    return TextStyle(
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w400,
        color: textDarkGreyColor);
  }

  TextStyle get text12BlackColor {
    return TextStyle(
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w400,
        color: blackColor,
        fontFamily: Regular);
  }

  TextStyle get text12BlackSemi {
    return TextStyle(
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w600,
        color: blackColor,
        fontFamily: Regular);
  }

  TextStyle get buttonBGColor12Semibold {
    return TextStyle(
        fontSize: getFontSize(12),
        color: buttonBGColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get white14Normal {
    return TextStyle(
        fontSize: getFontSize(14),
        color: whiteColor,
        fontWeight: FontWeight.normal);
  }

  TextStyle get white14Semibold {
    return TextStyle(
        fontSize: getFontSize(14),
        color: whiteColor,
        fontWeight: FontWeight.w600);
  }

  TextStyle get grey14Normal {
    return TextStyle(
        fontSize: getFontSize(14),
        color: textGray,
        fontWeight: FontWeight.normal);
  }

  TextStyle get grey12Normal {
    return TextStyle(
        fontSize: getFontSize(12),
        color: textGray,
        fontWeight: FontWeight.normal);
  }

  TextStyle get darkGrey14Normal {
    return TextStyle(
        fontSize: getFontSize(14),
        color: textDarkGreyColor,
        fontWeight: FontWeight.normal);
  }

  TextStyle get white14Light {
    return TextStyle(
        fontSize: getFontSize(14),
        fontWeight: FontWeight.w300,
        color: whiteColor);
  }

  TextStyle get primaryColor14Normal {
    return TextStyle(
        fontSize: getFontSize(14),
        color: colorPrimary,
        fontWeight: FontWeight.w400);
  }

  TextStyle get primaryColor14SemiBold {
    return TextStyle(
        fontSize: getFontSize(14),
        color: colorPrimary,
        fontWeight: FontWeight.w600);
  }

  TextStyle get red14Medium {
    return TextStyle(
        fontSize: getFontSize(14),
        color: redColor,
        fontWeight: FontWeight.w500);
  }

  TextStyle get red12Normal {
    return TextStyle(
        fontSize: getFontSize(12),
        color: redColor,
        fontWeight: FontWeight.w400);
  }

  TextStyle get textColor14Medium {
    return TextStyle(
        fontFamily: Regular,
        fontSize: getFontSize(14),
        fontWeight: FontWeight.w500,
        color: colorPrimary);
  }

  TextStyle get hintColor14Semibold {
    return TextStyle(
        fontSize: getFontSize(14),
        fontWeight: FontWeight.w600,
        color: hintColor);
  }

  TextStyle get hintColor14Medium {
    return TextStyle(
        fontSize: getFontSize(14),
        fontWeight: FontWeight.w500,
        color: hintColor);
  }

  TextStyle get hintColor14Normal {
    return TextStyle(
        fontSize: getFontSize(14),
        fontWeight: FontWeight.w400,
        color: hintColor);
  }

  TextStyle get black12Semibold {
    return TextStyle(
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w600,
        color: blackColor);
  }

  TextStyle get hintColor12Semibold {
    return TextStyle(
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w600,
        color: hintColor);
  }

  TextStyle get black12Normal {
    return TextStyle(
        fontFamily: Medium,
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w400,
        color: blackColor);
  }

  TextStyle get darkGrey12Medium {
    return TextStyle(
        fontFamily: Medium,
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w400,
        color: grey);
  }

  TextStyle get white12Normal {
    return TextStyle(
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w400,
        color: whiteColor);
  }

  TextStyle get white12Medium {
    return TextStyle(
        fontFamily: Medium,
        fontSize: getFontSize(12),
        fontWeight: FontWeight.w400,
        color: whiteColor);
  }

  TextStyle get text20SemiPrimary {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(20),
        fontWeight: FontWeight.w600,
        color: colorPrimary);
  }

  TextStyle get text22SemiPrimary {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(22),
        fontWeight: FontWeight.w600,
        color: colorPrimary);
  }

  TextStyle get text20SemiBlakc {
    return TextStyle(
        fontFamily: Semibold,
        fontSize: getFontSize(20),
        fontWeight: FontWeight.w600,
        color: blackColor);
  }
}

BaseTheme? get appTheme => ThemeHelper.theme();
