import 'package:admin/app/localization/AuthStrings.dart';
import 'package:admin/app/localization/CommonString.dart';
import 'package:admin/app/localization/ScreenTitle.dart';
import 'package:admin/app/localization/ThemeString.dart';

class R {
  static BaseLocale? string() => _getDefaultLocal();

  static String? _appLocale;

  static Map<String, BaseLocale> _supportedLocales = const {
    "en_us": ENLocale()
  };

  static BaseLocale? _getDefaultLocal() {
    //return default strings if locale is not set

    if (_appLocale == null) return BaseLocale();

    //throw exception to notify given local is not found or not generated by the generator

    if (!_supportedLocales.containsKey(_appLocale))
      throw Exception(
          "$_appLocale is not found.\n Make sure you have added this locale in JSON file\n Try running flutter pub run build_runner");

    //return locale from map

    return _supportedLocales[_appLocale!];
  }

  static void changeLocale(String newLocale) {
    _appLocale = newLocale;
  }
}

///base class for all language locales
class BaseLocale {
  ///sub classes
  final StringConstant stringConstant;
  final CommonString commonString;
  final ThemeStrings themeStrings;
  final ScreenTitle screenTitle;
  final AuthStrings authStrings;

  const BaseLocale({
    this.stringConstant = const StringConstant(),
    this.commonString = const CommonString(),
    this.themeStrings = const ThemeStrings(),
    this.screenTitle = const ScreenTitle(),
    this.authStrings = const AuthStrings(),
  });
}

///base class for any sub modules
class StringConstant {
  final String appName;

  const StringConstant({
    this.appName = "admin",
  });
}

//custom Local classes
class ENLocale extends BaseLocale {
  const ENLocale()
      : super(
          stringConstant: const StringConstant(appName: "App name in EN"),
        );
}
